# Generated by Django 5.0 on 2024-01-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_validation_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supreme_court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_id', models.CharField(max_length=50)),
                ('lawyer_id', models.CharField(max_length=50)),
                ('clerk_id', models.CharField(max_length=50)),
                ('client_id', models.CharField(max_length=50)),
            ],
        ),
    ]
