# Generated by Django 5.0 on 2024-02-01 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_supreme_court'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoreInfo',
        ),
        migrations.DeleteModel(
            name='Supreme_court',
        ),
        migrations.DeleteModel(
            name='Validation_Data',
        ),
    ]
